version: '3.9'

services:

  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    env_file:
      - .env
    command: >
      sh -c 'python manage.py runserver 0.0.0.0:8000'
    environment:
      - DEBUG=1
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    env_file:
      - .env


volumes:
  postgres-data: