# Generated by Django 4.1.5 on 2023-01-26 17:02

from django.db import migrations

from psqlextra.backend.migrations.operations import PostgresAddHashPartition


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        PostgresAddHashPartition(
            model_name="Comment",
            name="comment_pt1",
            modulus=3,
            remainder=0,
        ),
        PostgresAddHashPartition(
            model_name="Comment",
            name="comment_pt2",
            modulus=3,
            remainder=1,
        ),
        PostgresAddHashPartition(
            model_name="Comment",
            name="comment_pt3",
            modulus=3,
            remainder=2,
        ),

    ]
