# Generated by Django 4.1.5 on 2023-01-26 16:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import users.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('gender', models.CharField(choices=[('Male', 'Мужчина'), ('Female', 'Женщина'), ('Other', 'Другой')], max_length=150, verbose_name='Пол')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('email', models.EmailField(max_length=150, null=True, verbose_name='Email')),
                ('mobile_phone', models.CharField(db_index=True, max_length=11, unique=True, validators=[users.utils.validate_phone_number], verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=150, verbose_name='Тег')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тег пользователя',
                'verbose_name_plural': 'Теги пользователя',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Дата создания')),
                ('url', models.CharField(max_length=150, verbose_name='URL изображения')),
                ('is_main', models.BooleanField(default=False, verbose_name='Флаг основного фото')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Фото пользователя',
                'verbose_name_plural': 'Фото пользователя',
            },
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=150, verbose_name='Увлечение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Увлечение пользователя',
                'verbose_name_plural': 'Увлечения пользователя',
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(default=datetime.datetime.today, verbose_name='Дата отправки запроса')),
                ('approve_date', models.DateField(null=True, verbose_name='Дата принятия запроса')),
                ('user_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_1_friends', to='users.user', verbose_name='Первый пользователь')),
                ('user_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_2_friends', to='users.user', verbose_name='Второй пользователь')),
            ],
            options={
                'verbose_name': 'Друг пользователя',
                'verbose_name_plural': 'Друзья пользователя',
            },
        ),
    ]
